# Generated by Django 4.1.7 on 2023-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-do'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=50),
        ),
    ]
