# Generated by Django 4.1.6 on 2023-02-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
