# Generated by Django 4.1.7 on 2023-05-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
