# Generated by Django 4.1.7 on 2023-05-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', '-updated', '-created']},
        ),
    ]
