# Generated by Django 4.1.6 on 2023-02-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
