# Generated by Django 4.1.6 on 2023-02-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
