# Generated by Django 4.1.6 on 2023-02-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
