# Generated by Django 4.1.6 on 2023-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.AddField(
            model_name='task',
            name='status_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status_inProgress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status_toDo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
